vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: assets/image
            upload_destination: '%kernel.project_dir%/public/assets/image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        post_image:
            uri_prefix: '/uploads/post_images'
            upload_destination: '%kernel.project_dir%/public/uploads/post_images'
